[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vagus-decipher"
version = "1.0.0"
description = "Vagus-Decipher AI: Neural Decoding of Vagus Nerve Electrophysiology for Real-Time Prediction of Systemic Inflammatory Storms"
authors = [
    {name = "Samir Baladi", email = "gitdeeper@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Healthcare Industry",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]
dependencies = [
    "torch>=2.4.0",
    "numpy>=2.0.0",
    "scipy>=1.14.0",
    "pywavelets>=1.5.0",
    "filterpy>=1.4.5",
]

[project.urls]
"Homepage" = "https://vagus-decipher.netlify.app"
"Dashboard" = "https://vagus-decipher.netlify.app/dashboard"
"Documentation" = "https://vagus-decipher.netlify.app/documentation"
"Repository" = "https://github.com/gitdeeper12/Vagus-Decipher"
"GitLab" = "https://gitlab.com/gitdeeper12/Vagus-Decipher"
"PyPI" = "https://pypi.org/project/vagus-decipher"
"DOI" = "https://doi.org/10.5281/zenodo.20347323"

[tool.setuptools.packages.find]
where = ["."]
include = ["vagus_decipher*"]
